# Generated by Django 4.1.2 on 2022-10-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Publish')], default=0, null=True),
        ),
    ]
