# Generated by Django 4.1.2 on 2022-10-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_body_post_description_post_image_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.post')),
            ],
            bases=('app.post',),
        ),
    ]
