# Generated by Django 4.1.2 on 2022-10-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_newsletteremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
