# Generated by Django 4.1.2 on 2022-10-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_category_alter_categories_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['id']},
        ),
    ]
