# Generated by Django 4.1.2 on 2022-10-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_adminpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderpost',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
