# Generated by Django 4.1.2 on 2022-11-02 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_profile_username_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categories'),
        ),
    ]
