# Generated by Django 4.1.2 on 2022-11-02 12:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_sliderpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('slug', ckeditor.fields.RichTextField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
