# Generated by Django 4.1.2 on 2022-11-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingNews',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.post')),
            ],
            bases=('app.post',),
        ),
    ]
