# Generated by Django 4.1.2 on 2022-11-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_news_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image_link',
            new_name='image',
        ),
    ]
